### ISSUE TITLE
How to create the clusters for the dataset?

### ISSUE THREAD

**Issue by ll490187880** [filipradenovic/cnnimageretrieval-pytorch#1]
Hi,filip!Glad to see your marvelous work on image retrieval.
You wrote in your paper that the SfM can automatically select the training data,so I wonder that if  you can  share the code about the Structure-from-Motion system for the training data?So,we can use the code for our own data.

**Comment by filipradenovic** [comment]
Hello, the SfM system used to generate the training data is available online: https://github.com/colmap/colmap. When the 3D models are created it is simple to select positive pairs of images that are having enough inliers (co-observed 3D points in the same model).

**Comment by shayxurui** [comment]
> Hi,filip!Glad to see your marvelous work on image retrieval.
> You wrote in your paper that the SfM can automatically select the training data,so I wonder that if you can share the code about the Structure-from-Motion system for the training data?So,we can use the code for our own data.

hi, do you know how to use colmap to create my own dataset lab? thanks
