### ISSUE TITLE
Mean average precision results using the training parameters mentioned in README

### ISSUE THREAD

**Issue by itzsid** [filipradenovic/cnnimageretrieval-pytorch#23]
Hi @filipradenovic, 

Wondering if you have mAP results when running: 
```
python3 -m cirtorch.examples.train YOUR_EXPORT_DIR --gpu-id '0' --training-dataset 'retrieval-SfM-120k' 
            --test-datasets 'roxford5k,rparis6k' --arch 'resnet101' --pool 'gem' --loss 'contrastive' 
            --loss-margin 0.85 --optimizer 'adam' --lr 1e-6 --neg-num 5 --query-size=2000 
            --pool-size=20000 --batch-size 5 --image-size 362
```

I got these results after around 30 epochs:
```
>> roxford5k: Evaluating...
>> roxford5k: mAP E: 69.27, M: 52.5, H: 25.54
>> roxford5k: mP@k[1, 5, 10] E: [88.24 78.63 72.01], M: [87.14 78.86 71.29], H: [58.57 45.43 37.  ]
>> rparis6k: Evaluating...
>> rparis6k: mAP E: 84.64, M: 67.1, H: 41.5
>> rparis6k: mP@k[1, 5, 10] E: [100.    95.14  92.86], M: [100.    97.71  96.  ], H: [94.29 84.29 81.43]
```
Does these look correct?

Also the mAP plot looked something like the following when plotted after every epoch:
![newplot 16](https://user-images.githubusercontent.com/685789/48854721-6f542500-ed67-11e8-9e06-41c7dbc72c25.png)
![newplot 29](https://user-images.githubusercontent.com/685789/48854731-72e7ac00-ed67-11e8-8fb3-fc21bd184083.png)
![newplot 31](https://user-images.githubusercontent.com/685789/48854734-75e29c80-ed67-11e8-8e17-9576ba83e02d.png)

What training parameters should I change to achieve mAP of 65.3 and 40.0 for roxford5k (M and H)? 

Thanks!

**Comment by filipradenovic** [comment]
The default training is done without whitening, and evaluation during training is also done without whitening as post-processing. That is why you see lower numbers, although your network is likely training as expected. 

To evaluate your network with multi-scale and whitening as post-processing run the test example script for any network-epoch:
```
python3 -m cirtorch.examples.test --gpu-id '0' --network-path YOUR_NETWORK_PATH 
                --datasets 'oxford5k,paris6k,roxford5k,rparis6k'
                --whitening 'retrieval-SfM-120k' --multiscale
```

Another option is to evaluate with whitening while training, but bear in mind that this will significantly slow down you training procedure, and it is not recommended:
```
python3 -m cirtorch.examples.train YOUR_EXPORT_DIR --gpu-id '0' --training-dataset 'retrieval-SfM-120k' 
            --test-datasets 'roxford5k,rparis6k' --test-whiten 'retrieval-SfM-30k' 
            --arch 'resnet101' --pool 'gem' --loss 'contrastive' --loss-margin 0.85 
            --optimizer 'adam' --lr 1e-6 --neg-num 5 --query-size=2000 --pool-size=20000 
            --batch-size 5 --image-size 362
```

**Comment by itzsid** [comment]
Thanks @filipradenovic!
