### ISSUE TITLE
did you try to learn GeM by a set of learnable parameters instead of a single parameter?

### ISSUE THREAD

**Issue by youmingdeng** [filipradenovic/cnnimageretrieval-pytorch#26]
Hi filip, thank you for your excellent work.
In the paper, you said that
"In this case pk = p; k \in [1, K] and we simply denote it by p and not pk."
The reason is that a set of parameters are hard to learn or bad performance.

**Comment by filipradenovic** [comment]
If you take a look at Table 1 in the paper, last two rows are for the case when we learn a set of parameters {pk}, instead of a single parameter p. The performance is always slightly worse compared to the case of a single parameter learning.
