### ISSUE TITLE
Why compute_ap() does not generate correct result?

### ISSUE THREAD

**Issue by liut0012** [filipradenovic/cnnimageretrieval-pytorch#29]
Hi, I am testing the part that generates the mAP, and it does not generate correct answer. 

I checked the details of the code and it is due to this part: 

https://github.com/filipradenovic/cnnimageretrieval-pytorch/blob/bea5aed4361acf2193348064aa9b35d9f48e956d/cirtorch/utils/evaluate.py#L28-L35

Could you explain why it is not simply written as  
`        ap += (precision_1) * recall_step
`?

Many thanks!

**Comment by liut0012** [comment]
I understand the difference. CIR computes the area under PR curve as the sum of areas of a sequence of trapeziums, while in the traditional information retrieval, the area is the sum of areas of a sequence of rectangles.

**Comment by AbyssGaze** [comment]
why precision_1 formula not:
```
            precision_1 = float(j + 1) / (rank[j+1])
```
thanks

**Comment by ltm920716** [comment]
> I understand the difference. CIR computes the area under PR curve as the sum of areas of a sequence of trapeziums, while in the traditional information retrieval, the area is the sum of areas of a sequence of rectangles.

hello @liut0012,
Could you please explain it more specifically? I'm still confused, thanks!
