### ISSUE TITLE
How to Choose the Number of Positive and Negative pairs

### ISSUE THREAD

**Issue by nuaawzl** [filipradenovic/cnnimageretrieval-pytorch#33]
Hi Filip,
    For your dataset like retrieval-SfM-120k.pkl, 1 query + 1 positive + 5 negative for training. I want use more positive and negative pairs, such as 1 query + 8 positive + 16 negative. Do you have any suggestions or experiences to share?  thanks

**Comment by filipradenovic** [comment]
Hi,

There is a parameter in the training script `--neg-num 5` which you can set to any number of negative images you want. In your case, it would be `--neg-num 16`.

Now, we don't have a similar thing for positives, but if you take a look in the code, specifically the function [create_epoch_tuples()](https://github.com/filipradenovic/cnnimageretrieval-pytorch/blob/1571dc22a5f97541e483ddc78930e99bc969101d/cirtorch/datasets/traindataset.py#L153) you can see how the positives and negatives are selected. With a bit of code change, it is possible to have multiple positives for each query.
