### ISSUE TITLE
How can I test wiht Flickr100k

### ISSUE THREAD

**Issue by hill2hill** [filipradenovic/cnnimageretrieval-pytorch#34]
Excuse me, sir:
    During our experiment, we would like to test the performance not only on Oxford5k or Paris6k. We want to try test on Oxford105k and Paris106k dataset. Can you tell me any tip I should prepare for this bigger dataset? Such as a new combined ground_truth file or save it in which path or it's still ok keeping oxford/paris ground_truth separate with Flickr100k's ground truth file ?
                                                                                                                    Thank you so much.

**Comment by hill2hill** [comment]
Just append it after 'image' in test.py

**Comment by filipradenovic** [comment]
> Just append it after 'image' in test.py

Exactly correct.
