### ISSUE TITLE
cannot download the dataset

### ISSUE THREAD

**Issue by SongZRui** [filipradenovic/cnnimageretrieval-pytorch#36]
It seems that the url has expired. Do you have any alternative download address?

**Comment by filipradenovic** [comment]
All the data is available at the same urls. However, it seems that there are some network issues with addresses hosting the data at the moment, so the downloading could be very slow. I will look into it with our admin service, resolve it, and get back to you.

**Comment by filipradenovic** [comment]
It should be resolved now. We are currently working on improving the hosting service where the data is stored. Thank you for raising this issue.

**Comment by yohohohoho** [comment]
> It seems that the url has expired. Do you have any alternative download address?

Hello, do you download pretrained weights? Could you send me a copy?
