### ISSUE TITLE
Running the toolbox on Windows

### ISSUE THREAD

**Issue by SongZRui** [filipradenovic/cnnimageretrieval-pytorch#39]
As we know from the script, there are some Linux shell command in the download.py, such as 'wget', 'rm', 'rm -rf', etc. Actually, we can easily find alternative commands in windows 10. Here I summon a brief list:
wget: you can download and install wget directly from [here](http://gnuwin32.sourceforge.net/packages/wget.htm), where you can choose *64 or *86 architecture.
rm: del (remove files)
rm -rf : rd(remove directories)
[download.txt](https://github.com/filipradenovic/cnnimageretrieval-pytorch/files/3219561/download.txt)

The attachment is a modified script that works properly on windows 10. Because git do not support supply with a .py file, it has been renamed into .txt. But I am pretty sure that it works.

**Comment by filipradenovic** [comment]
Thank you very much! When updating the code I will add this script for usage on windows.

**Comment by filipradenovic** [comment]
I added the script in utils as [download_win.py](https://github.com/filipradenovic/cnnimageretrieval-pytorch/blob/master/cirtorch/utils/download_win.py).
