### ISSUE TITLE
Cannot download datasets

### ISSUE THREAD

**Issue by yohohohoho** [filipradenovic/cnnimageretrieval-pytorch#42]
It seems that all the links have failed. Are there any other links available?

**Comment by filipradenovic** [comment]
We haven't noticed any problem with the download of datasets at this point. Can you try again?

**Comment by filipradenovic** [comment]
#
Duplicate of #36

**Comment by yohohohoho** [comment]
> We haven't noticed any problem with the download of datasets at this point. Can you try again?
> 
> Duplicate of #36

Thank you. I downloaded the entire data set after changing the VPN.
