### ISSUE TITLE
Why 'qidxs' and 'pidxs' are required in database?

### ISSUE THREAD

**Issue by duchengyao** [filipradenovic/cnnimageretrieval-pytorch#5]
Thanks for your great work on image retrieval!

I found your training data `retrieval-SfM-120k.pkl` include `['cids', 'qidxs', 'pidxs', 'cluster']`. 
After generate clusters, why I have to create positive pairs of images(qidxs,pidxs). 

Thanks!

**Comment by filipradenovic** [comment]
Clusters are generated using a 3D structure-from-motion reconstruction. Many clusters are really big, so two images from the same cluster are not necessarily depicting the same part of the scene. For that reason, we cannot use any two images from the same clusters as positive pair. We used the inlier information to create (qidxs, pidxs) pairs.

**Comment by duchengyao** [comment]
Thank you for answering my question!
