### ISSUE TITLE
Train code for GL18 Dataset

### ISSUE THREAD

**Issue by tonyngjichun** [filipradenovic/cnnimageretrieval-pytorch#55]
Hi filip,

would you be able to release the part of code that loads positives and negative images from the gl18 dataset? That would be very helpful.

Thanks!

**Comment by benjamink85** [comment]
Hey @tonyngjichun - any progress on this?

**Comment by tonyngjichun** [comment]
@benjamink85 hi yes, my repo has the code now to pre-process gl18: https://github.com/tonyngjichun/SOLAR#training-solar
