### ISSUE TITLE
Pretrained weight used in "Attention-Based Query Expansion Learning"

### ISSUE THREAD

**Issue by XiSHEN0220** [filipradenovic/cnnimageretrieval-pytorch#67]
Hi, thanks for your effort to maintain the repo!!!

I am interested in your ECCV paper  [Attention-Based Query Expansion Learning](https://arxiv.org/pdf/2007.08019.pdf). 

In the paper, you describe that 
"We use the best-performing model from the project page (trained on Google Landmarks 2018 data [29]), consisting of a ResNet101 trunk followed by generalized-mean pooling and a whitening layer, which produces features of 2048 dimensions.
"

The pretained ResNet101 should be somewhere in the repo but I cannot find it. 
The one trained on sfm is with lower performance.

Is it possible to have a direct link here? 

Thanks a lot, 
Best

**Comment by XiSHEN0220** [comment]
Hi, 

I think I find the good model.
I ran the test with the following command: 

`python3 -m cirtorch.examples.test --gpu-id '0' --network-path 'gl18-tl-resnet101-gem-w' --datasets 'oxford5k,paris6k,roxford5k,rparis6k' --whitening 'retrieval-SfM-120k' --multiscale '[1, 1/2**(1/2), 1/2]'`

I obtained the perf:
![image](https://user-images.githubusercontent.com/11667167/96972562-f3485600-1516-11eb-8fc0-6094e8fbd2f1.png)

which is slightly lower than what you reported in the ECCV paper (Tab.2 No QE).

Could you provide some help to reproduce this results such that I could make everything comparable? 

Thanks

**Comment by filipradenovic** [comment]
Please check the section in README: "Testing our pretrained networks with whitening learned end-to-end". Note that it is expandable, you will see the running command and the tables with results that match the LAttQE paper:

```
python3 -m cirtorch.examples.test_e2e --gpu-id '0' --network 'gl18-tl-resnet101-gem-w' 
            --datasets 'roxford5k,rparis6k' --multiscale '[1, 2**(1/2), 1/2**(1/2)]'
```

**Comment by XiSHEN0220** [comment]
Hi, thanks a lot for your reply!!!

I tried your command, but cannot obtain the performance reported in the [table](https://github.com/filipradenovic/cnnimageretrieval-pytorch#networks-with-whitening-learned-end-to-end) 

This is a screenshot. 
![image](https://user-images.githubusercontent.com/11667167/97190867-8d71fd80-17a6-11eb-8d69-9b2a9e0c586d.png)

I am using Pytorch 1.2.0 (in the readme, you clarify that it was tested under Pytorch 1.0.0), do you think this might be the reason? 

But it remains weird. 

Thanks again for your help. 

Best

**Comment by XiSHEN0220** [comment]
Sorry, 
I made a stupid mistake about the multiscale parameter. 

Now I can obtain exactly the same results as you did. 

Thanks a lot!!!

Best
