### ISSUE TITLE
finding positive pairs

### ISSUE THREAD

**Issue by RuibinMa** [filipradenovic/cnnimageretrieval-pytorch#7]
Hi Filip,
For your dataset like retrieval-SfM-120k.pkl, did you find a positive pair for each image in 'cids' (if exist)?
I'm trying to build my own dataset using exactly the same approach as yours, using colmap.
Do you plan to publish the code for extracting the positive pairs?
Thank you very much!

**Comment by filipradenovic** [comment]
For now, we are not planning to publish the code for extracting the positive pairs. You can do it using colmap. However, you do not need positive pair for each image in 'cids', a subset is enough. The image that do not have corresponding positive pair can still be used as negative examples.

**Comment by RuibinMa** [comment]
I see. Thank you!
