### ISSUE TITLE
why 'qidxs' equals 'pidxs' sometimes? 

### ISSUE THREAD

**Issue by RuibinMa** [filipradenovic/cnnimageretrieval-pytorch#9]
I read in the 'retrieval-SfM-120k.pkl' using pickle. Then I checked whether the two corresponding values in qidxs and pidxs are different (They should be different, right? Because query and positive image should not be the same picture). However, I found some pairs have equal image idxs:

>>> count = 0
>>> for q, p in zip(data['train']['qidxs'], data['train']['pidxs']):
...   if q == p:
...     count += 1
... 
>>> count
47

47 pairs out of 181697 pairs have the same idx value. Is that normal or a bug?
Thanks!

**Comment by filipradenovic** [comment]
Query-positive pairs were selected from SfM reconstructed models. After that, each image is hashed using its content to create the CID unique name for the image. During this process, something like this happens: two images with different names in the dataset (hence not considered unique) are selected to be query-positive, and after hashing they are mapped into the same hash thus receiving the same index, ie `qidx==pidx`. Given that there is, as you said, only 47 out of 181697 pairs we did not considered this to be an issue, and the dataset was not updated to remove such pairs. If you want, you can remove them, but it will not make a difference for the training.

**Comment by RuibinMa** [comment]
Thanks! Helpful comments.
